version: '3'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - ${DB_PORT}:3306

  api:
    build:
      context: ./api
      args: 
        - WORKDIR=${WORKDIR}
    environment:
      - FRONT_URL=http://localhost:${FRONT_PORT}
      - DB_USER_NAME=${DB_USER_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
    volumes:
      - ./api/app:/${WORKDIR}/app
      - /${WORKDIR}/app/__pycache__/
    command: uvicorn app.main:app --host 0.0.0.0 --reload
    ports:
      - ${API_PORT}:8000
    depends_on:
      - db

  front:
    build:
      context: ./front
      args: 
        - WORKDIR=${WORKDIR}
    environment:
      - REACT_APP_API_URL=http://localhost:${API_PORT}
      - CHOKIDAR_USEPOLLING=true
    command: yarn start
    volumes:
      - ./front/src:/${WORKDIR}/src
    ports:
      - ${FRONT_PORT}:3000
    depends_on:
      - api

volumes:
  mysql_data: